good

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -22,14 +22,16 @@ jobs:
           temp_file=$(mktemp)
 
           for file in _posts/*; do
+            echo "Processing file: $file"
+            # 获取原始文件名，用于显示
+            pretty_name=$(basename "$file")
+            # 获取URL编码后的文件名，用于链接
+            url_name=$(basename "$file" | sed 's/ /%20/g')
+            git log -1 --format="%ad" --date=short -- $url_name || echo "git log failed for $file"
             # 检查文件是否有git提交记录
             if git log -- $file > /dev/null 2>&1; then
               # 获取文件的最后提交日期
               lastDate=$(git log -1 --format="%ad" --date=short -- $file)
-              # 获取原始文件名，用于显示
-              pretty_name=$(basename "$file")
-              # 获取URL编码后的文件名，用于链接
-              url_name=$(basename "$file" | sed 's/ /%20/g')
               # 将日期、原始文件名（用于显示）和URL编码后的文件名（用于链接）写入临时文件
               echo "$lastDate - [$pretty_name](_posts/$url_name)" >> $temp_file
             else
